### ISSUE TITLE
Error when trying to obtain explanations for a particular program. Possibly because of aggregates?

### ISSUE THREAD

**Issue by bramucas** [alviano/xasp#2]
```
% polluted_river.lp

river(rin).
factory(a).
factory(b).
farm(c).

chemical(a, rin, 30). chemical(b, rin, 60). chemical(c, rin, 10).
nutrient(c, rin, 30).

entity(E, factory) :- factory(E).
entity(E, farm) :- farm(E).

polluted_river(River) :- 
    river(River), 
    #sum{P1: entity(E, T), chemical(E, River, P1); P2: entity(E, T), nutrient(E, rin, P2)}=Sum, 
    Sum>50.
```

This program outputs an error when executed using the following Python code:
```python
from xasp.entities import Explain
from dumbo_asp.primitives import Model

with open("polluted_river.lp", "r") as rfile:
    prog = rfile.read()
query = "polluted_river(rin)"

explain = Explain.the_program(
    prog,
    the_answer_set=Model.of_program(prog),
    the_atoms_to_explain=Model.of_atoms(query),
)

explain.compute_igraph()  # for generating a html version of the graphs
explain.show_navigator_graph()

print(explain.explanation_dags)
```

Apparently, the error is due to the aggregate in the `polluted_river/1` rule. Removing the last two lines removes the error and a graph is open in the browser.

**Comment by bramucas** [comment]
The error:

```
(xasp) user@machine:~/folder/xasp/myexample$ python example.py 
Traceback (most recent call last):
  File "/home/user/folder/xasp/myexample/example.py", line 20, in <module>
    explain = Explain.the_program(
  File "/home/user/folder/xasp/xasp/entities.py", line 69, in the_program
    res.__compute_serialization()
  File "/home/user/folder/xasp/xasp/entities.py", line 299, in __compute_serialization
    transformed_program = transformer.apply(self.asp_program + '\n'.join(f":- {atom}, -{atom}."
  File "/home/user/folder/xasp/xasp/transformers.py", line 26, in apply
    raise self.__exceptions[0]
  File "/home/user/folder/xasp/xasp/transformers.py", line 31, in __transform
    self.visit(obj)
  File "/home/velka/anaconda3/envs/xasp/lib/python3.10/site-packages/clingo/ast.py", line 1401, in visit
    return getattr(self, attr)(ast, *args, **kwargs)
  File "/home/user/folder/xasp/xasp/transformers.py", line 102, in visit_Rule
    self.__process_aggregate(literal, rule_id, rule_atom, variables)
  File "/home/user/folder/xasp/xasp/transformers.py", line 201, in __process_aggregate
    validate("condition", element.condition, length=1)
  File "/home/velka/anaconda3/envs/xasp/lib/python3.10/site-packages/valid8/entry_points_inline.py", line 314, in validate
    raise_(err)
  File "/home/velka/anaconda3/envs/xasp/lib/python3.10/site-packages/valid8/base.py", line 71, in raise_
    raise exc
valid8.entry_points.ValidationError[ValueError]: Error validating [condition]. WrongLength: len(x) == 1 does not hold for x=(too big for display). Wrong value: (Actual value is too big to be printed in this message).
``

**Comment by alviano** [comment]
Hi Brais,

Yes, it is due to the aggregate. We only support a limited syntax for
aggregates: one atomic element in the aggregate set, no value invention, no
recursion.

Replacing

polluted_river(River) :-
    river(River),
    #sum{P1: entity(E, T), chemical(E, River, P1); P2: entity(E, T),
nutrient(E, rin, P2)}=Sum,
    Sum>50.

by

polluted_river(River) :-
    river(River),
    #sum{P: __aggregate_set(P,River)}=Sum,
    Sum = 51..1000.  % a reasonable bound for this variable, maybe 100 if
it is a percentage
__aggregate_set(P1,River) :- entity(E, T), chemical(E, River, P1).
__aggregate_set(P2,River) :- river(River), entity(E, T), nutrient(E, rin,
P2).  % very likely it can be rewritten better by splitting the aggregate

I get the graph
https://xasp-navigator.netlify.app/#eJzllMGOmzAQhl/FclWJSF5kQ8ImVNtb7lG7t2YVGeKmqAQiY6quorx7jQ1rJ8ar7CHKoZzA+PvnH8+Mj7Cqt6yB6Y8jLLYwxQiWNGMlTCEv/jAe8KKarKumPRxqLiCCf2H6QMIZgq8wJSE+Ic0Rw/2kfB/kDhSHWEFTA0U2lIuavwbZJYddLHYxeokRF5saLP/F9kVOyyBHMj9EsON22vOx4WcjfKb4xOWJyycjPFV87PKRyz8anlWiEDJr1Ofvy96i5w6d+Wjs0guHzlFXZ2+VLZZYPbXZ0N2Osx0VbNMwEch/Yw02qESWCvGrJOMquG9TWyXyq8SjKmTEitWAUoIEuofcIuKRObG68FCXZSvYdvPepOnosiSnF0kW1W89q03d8pypphCU75g4G4u+RksEhhKD9GF4D5aTcF0twdNXQGHna9CaG63o41rZmdbCaJFxLdk8WkjeFkYlP1PpWmeQmfortyLoW3eEStDEeJ4g8DZp8lvtQWBFVDQ0UOhZBUa6F1Vbe00s7maCGBOz25rIUDKYUDX2+pjf00dkfCS39UFRfJ2Px3v6iK2Bsy7cT027P65S4Bjq/Zyevrf7daXDyNcuUH+d+fWjG+uTG+hPLf3Yewe/FWldAfnYi0gvfQbaEkmvquMXsIoud1at4IVc6r47r3KLzqMPcVXO/V6VMpiRMJQZ4/CDJ4H/u4N4Of0D/2RjuQ==%21

There was also a bug on the aggregate IDs, which is now fixed (pull to get
the update).

Many thanks for asking and let me know if I can do more.

All the best,
Mario

**Comment by bramucas** [comment]
Thank you very much for the quick response.

I wasn't aware of this. I guess you have plans to support it in the future?

Feel free to close the issue or to leave it open as a TODO task.

Thank you Again!
Brais.
